Krafton-Jungle-Weight/Codeplanner_Backend

package-lock.json, package.json, src/app.module.ts, src/database/database.module.ts, src/main.ts, src/project/dto/create-project.dto.ts, src/project/dto/index.ts, src/project/dto/project-response.dto.ts, src/project/dto/update-project.dto.ts, src/project/project-member.entity.ts, src/project/project.controller.ts, src/project/project.entity.ts, src/project/project.module.ts, src/project/project.service.ts, src/user/user.entity.ts, src/user/user.module.ts
프로젝트 관련 Postgre SQL 연동 및 DTO 생성 완료. 코드 설명 주석까지 추가 완료 했습니다.
자세한 사항은 커밋 목록을 확인해주세요.
=> 프로젝트 관련 Postgre SQL 연동 및 DTO 생성 완료. 코드 설명 주석까지 추가 완료 했습니다.

src/database/database.module.ts
=> fix(database): DB 설정파일 재 수정

.env.development, .env.production, src/database/database.module.ts, src/database/database.provider.ts
25/07/01 아마존 RDS를 연결하기 위해 환경에 따라 동적으로 DB를 불러옴. DB 연결 준비 완료
=> 25/07/01 아마존 RDS를 연결하기 위해 환경에 따라 동적으로 DB를 불러옴

.github/workflows/deploy.yml
=> 25/07/01 dev에 깃허브 액션 파일 추가

.env.production
25/07/01 deplaoy 파일 연결관련 ip주소 수정(잘못 작성함)
=> 25/07/01 deplaoy 파일 연결관련 ip주소 수정(잘못 작성함)

src/auth/auth.controller.ts, src/email/email.controller.ts, src/main.ts, src/project/project.controller.ts, src/user/user.controller.ts
25/07/01 CORS 해결을 위한 api url 프리피스 설정
=>  25/07/01 CORS 해결을 위한 api url 프리피스 설정

ecosystem.config.js
=> 25/07/02 BASE_URL 업데이트

src/summary/summary.controller.ts
25/07/02 요약, 보드, 목록 페이지 못가져오는 문제 해결중
=> 25/07/02 요약, 보드, 목록 페이지 못가져오는 문제 해결중

src/issues/issues.controller.ts, src/project/project.controller.ts, src/project/project.service.ts, src/timeline/timeline.controller.ts, src/timeline/timeline.module.ts, src/user/user.controller.ts, src/user/user.service.ts
Reverts Krafton-Jungle-Weight/Codeplanner_Backend#51
=> Revert "New jh"

src/issues/issues.controller.ts, src/issues/issues.service.ts
=> 07/02 충돌 방지용 merge

src/auth/auth.controller.ts, src/user/user.controller.ts
=> 2025/07/03 이메일인증 핫픽스

.env.development, .env.production, src/github/github.controller.ts, src/github/github.service.ts
=> 25-07-05 웹훅 fix

src/github/github-commits.entity.ts, src/github/github-webhook.controller.ts, src/github/github-webhook.service.ts, src/github/github.controller.ts, src/github/github.module.ts, src/github/github.service.ts, src/issues/issues.controller.ts, src/issues/issues.entity.ts, src/issues/issues.service.ts
=> 25-07-05 커밋 이슈 연결 및 추가기능 구현

src/github/github.controller.ts
25-07-07 브랜치, 레포 자동생성, 회의록을 기반으로 자동 티켓 생성, 웹훅 생성 및 티켓과 커밋 연결 과 추가 기능.
=> 25-07-07 브랜치, 레포 자동생성, 회의록을 기반으로 자동 티켓 생성, 웹훅 생성 및 티켓과 커밋 연결 과 추가 기능.

src/aimodel/aimodel.service.ts, src/github/github.service.ts
(2025/07/07) AI 자동 이슈 생성 인터페이스 완성
=> (2025/07/07) AI 자동 이슈 생성 인터페이스 완성

src/aimodel/aimodel.service.ts, src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/auth/dto/verify-reset-token.dto.ts, src/email/email.service.ts, src/user/user.service.ts
=> (2025/07/08) Ai 개선

src/comments/comment.controller.ts, src/comments/comment.dto.ts, src/comments/comment.service.ts, src/notification/notification.service.ts
=> 25-07-08 이슈 댓글 기능 구현

src/aimodel/aimodel.service.ts, src/comments/comment.service.ts
=> 25-07-08 백로그 추가

src/analysis/analysis.module.ts, src/analysis/analysis.service.ts, src/analysis/dto/analyze-request.dto.ts, src/analysis/scanner/clang-format.scanner.ts, src/analysis/scanner/clang-tidy.scanner.ts, src/auth/auth.controller.ts
07/08 feat(analysis) 포메터도 같이 검사 진행
=> 07/08 feat(analysis) 포메터도 같이 검사 진행

src/analysis/scanner/clang-tidy.scanner.ts, src/analysis/scanner/cppcheck.scanner.ts
07/09 feat(analysis): 분석기 os별 적용 수정
=> 07/09 feat(analysis): 분석기 os별 적용 수정

src/issues/issue_label.entity.ts, src/issues/issues-update.dto.ts, src/issues/issues.controller.ts, src/issues/issues.entity.ts, src/issues/issues.module.ts, src/issues/issues.service.ts, src/issues/label.entity.ts, src/main.ts, src/project/dto/label.dto.ts, src/project/project.controller.ts, src/project/project.entity.ts, src/project/project.module.ts, src/project/project.service.ts, src/summary/summary.module.ts, src/user/user.controller.ts, src/user/user.service.ts
=> 25-07-11 레이블 추가

src/analysis/scanner/base.scanner.ts, src/analysis/scanner/clang-format.scanner.ts, src/analysis/scanner/clang-tidy.scanner.ts, src/analysis/scanner/cppcheck.scanner.ts
07/12 CP-43 코드 검사기에 대한 json 구조 추가, issues배열 담을 변수
=> 07/12 CP-43 코드 검사기에 대한 json 구조 추가, issues배열 담을 변수

src/analysis/scanner/cppcheck.scanner.ts, test_fixed.c
07/12 CP-43 코드 검사기 필터링 추가 (헤더 관련 메세지 필터링)
=> 07/12 CP-43 코드 검사기 필터링 추가 (헤더 관련 메세지 필터링)

src/github/github-webhook.service.ts, src/notification/notification.service.ts
25-07-14 칸반보드 가로스크롤 개선 및 필터링 기능 추가, 프로필 부분 개선, 이슈카드 담당자 추가
=> 25-07-14 칸반보드 가로스크롤 개선 및 필터링 기능 추가, 프로필 부분 개선, 이슈카드 담당자 추가

src/project/project.controller.ts, src/project/project.service.ts
=> 25-07-16 레이블 삭제 기능

src/summaryai/summaryai.service.ts
25/07/18 Summary Ai 기여도에서 내 이슈 집계 정상화
=> 25/07/18 Summary Ai 기여도에서 내 이슈 집계 정상화

src/comments/comment.service.ts, src/summaryai/summaryai.service.ts
25/07/19 Summary Ai 프롬프트 최적화, 보내는 정보 정제, Ai 더블 체크로 정확성 증가, 가비지 값 예외처리
=> 25/07/19 Summary Ai 프롬프트 최적화, 보내는 정보 정제, Ai 더블 체크로 정확성 증가, 가비지 값 예외처리

src/aimodel/aimodel.service.ts, src/comments/comment.service.ts, src/summaryai/summaryai.service.ts
=> 2025/07/19 AI 모델 한번 검토 과정

src/activity/activity.service.ts, src/aimodel/aimodel.service.ts, src/comments/comment.service.ts, src/issues/issues.service.ts, src/summaryai/summaryai.service.ts
25/7/19 리뷰어 검색 ui개선, 중복로깅 방지 로직추가
=> 25/7/19 리뷰어 검색 ui개선, 중복로깅 방지 로직추가
